function FineCross(window, Cross, Fgnd, Bgnd, Mgnd)
%Puts a fixation cross in the centre of window.

if nargin < 2
    Cross = '+';
    Fgnd = [255 255 255];
    Bgnd = [0 0 0];
    Mgnd = [127 127 127];
elseif nargin < 3
    Fgnd = [255 255 255];
    Bgnd = [0 0 0];
    Mgnd = [127 127 127];
elseif nargin < 4
    Bgnd = [0 0 0];
    Mgnd = [127 127 127];
elseif nargin < 5
    Mgnd = [127 127 127];
end

for c = 1:3
    X = Fgnd(c);
    O = Bgnd(c);
    m = Mgnd(c);
    % Fixation point image
    switch Cross  
        case 'x' % St Andrews cross
            fixptimg(:,:,c) = [m m m O O m m m; ...
                               m X X O O X X m; ...
                               m X X X X X X m; ...
                               O O X X X X O O; ...
                               O O X X X X O O; ...
                               m X X X X X X m; ...
                               m X X O O X X m; ...
                               m m m O O m m m];
        case '+' % Christian cross
            fixptimg(:,:,c) = [m m m X X m m m; ...
                               m O O X X O O m; ...
                               m O O X X O O m; ...
                               X X X X X X X X; ...
                               X X X X X X X X; ...
                               m O O X X O O m; ...
                               m O O X X O O m; ...
                               m m m X X m m m];
        case 'o' % Just a circle 
            fixptimg(:,:,c) = [m m m O O m m m; ...
                               m O O O O O O m; ...
                               m O O O O O O m; ...
                               O O O O O O O O; ...
                               O O O O O O O O; ...
                               m O O O O O O m; ...
                               m O O O O O O m; ...
                               m m m O O m m m];
    end
end

winRect  = Screen('Rect', window);  %returns screen dimensions
Screen('PutImage', window, fixptimg, CenterRect([0 0 size(fixptimg,2) size(fixptimg,1)], winRect));


